services:
  - type: web
    name: kammit-api
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/elvis
    envVars:
      - key: PORT
        value: 8080
